version: '3'
services:

  owncloud1:
    image: owncloud/server:10.12.0
    container_name: owncloud1
    restart: always
    ports:
      - "8080:8080"
    environment:
      OWNCLOUD_DOMAIN: localhost 
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: owncloud
      OWNCLOUD_DB_USERNAME: owncloud
      OWNCLOUD_DB_PASSWORD: owncloud
      OWNCLOUD_DB_HOST: mysql
      OWNCLOUD_ADMIN_USERNAME: user     
      OWNCLOUD_ADMIN_PASSWORD: pass  
      OWNCLOUD_MYSQL_UTF8MB4: true
      OWNCLOUD_REDIS_ENABLED: true
      OWNCLOUD_REDIS_HOST: redis
    depends_on:
      - redis
      - openldap
      - mysql
    volumes:
      - files_owncloud:/mnt/data
    networks:
      - net


  mysql:
    image: mariadb:10.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111
      MYSQL_PORT: 3306
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: owncloud
      MYSQL_DATABASE: owncloud
      MYSQL_LOWER_CASE_TABLE_NAMES: 0
    volumes:
      - data_mysql_master:/var/lib/mysql
    networks:
      - net

  redis:
    image: redis:7
    container_name: redis
    restart: always
    environment:
      REDIS_DATABASES: 1
    volumes:
      - redis_cache:/data
    networks:
      - net

  openldap:
    image: osixia/openldap:latest
    restart: unless-stopped
    ports:
      - 389:389
    environment:
      LDAP_ORGANISATION: Cloud Computing
      LDAP_DOMAIN: cloud.com 
      LDAP_ADMIN_PASSWORD: admin
    volumes:
      - ./data/openldap/var_lib_ldap:/var/lib/ldap
      - ./data/openldap/etc_ldap_slapd.d:/etc/ldap/slapd.d
    networks:
      - net

networks:
  net:

volumes:
  haproxy_conf:
    driver: local
  data_mysql_master:
    driver: local
  redis_cache:
    driver: local
  openldap_data:
    driver: local
  files_owncloud:
    driver: local 
