version: '3'
services:

  haproxy:
    image: haproxy:1.6
    container_name: haproxy
    restart: always
    depends_on:
      - owncloud1
      - owncloud2
    ports:
      - '80:80'
    volumes:
      - haproxy_conf:/usr/local/etc/haproxy
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - net


  owncloud1:
    image: owncloud/server:10.12.0
    container_name: owncloud1
    restart: always
    expose:
      - 8080
    environment:
      OWNCLOUD_DOMAIN: localhost 
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: owncloud
      OWNCLOUD_DB_USERNAME: owncloud
      OWNCLOUD_DB_PASSWORD: owncloud
      OWNCLOUD_DB_HOST: mysql
      OWNCLOUD_ADMIN_USERNAME: user     
      OWNCLOUD_ADMIN_PASSWORD: pass  
      OWNCLOUD_MYSQL_UTF8MB4: true
      OWNCLOUD_REDIS_ENABLED: true
      OWNCLOUD_REDIS_HOST: redis
    depends_on:
      - redis
      - openldap
      - mysql
    volumes:
      - files_owncloud:/mnt/data
    networks:
      - net

  owncloud2:
    image: owncloud/server:10.12.0
    container_name: owncloud2
    restart: always
    expose:
      - 8080
    environment:
      OWNCLOUD_DOMAIN: localhost 
      OWNCLOUD_DB_TYPE: mysql
      OWNCLOUD_DB_NAME: owncloud
      OWNCLOUD_DB_USERNAME: owncloud
      OWNCLOUD_DB_PASSWORD: owncloud
      OWNCLOUD_DB_HOST: mysql
      OWNCLOUD_ADMIN_USERNAME: user      
      OWNCLOUD_ADMIN_PASSWORD: pass  
      OWNCLOUD_MYSQL_UTF8MB4: true
      OWNCLOUD_REDIS_ENABLED: true
      OWNCLOUD_REDIS_HOST: redis
    depends_on:
      - redis
      - openldap
      - mysql
    volumes:
      - files_owncloud:/mnt/data
    networks:
      - net

  mysql:
    image: mariadb:10.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111
      MYSQL_PORT: 3306
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: owncloud
      MYSQL_DATABASE: owncloud
      MYSQL_LOWER_CASE_TABLE_NAMES: 0
    volumes:
      - data_mariadb:/var/lib/mysql
    networks:
      - net

  redis:
    image: redis:7
    container_name: redis
    restart: always
    environment:
      REDIS_DATABASES: 1
    volumes:
      - redis_cache:/data
    networks:
      - net

  openldap:
    image: bitnami/openldap:2.5
    container_name: openldap
    restart: always
    ports:
      - "389:1389"
    environment:
      LDAP_ORGANISATION: Cloud Computing
      LDAP_DOMAIN: cloud.com
      LDAP_ROOT: dc=cloud,dc=com
      LDAP_ADMIN_PASSWORD: admin
    volumes:
      - openldap_data:/bitnami/openldap
    networks:
      - net

networks:
  net:

volumes:
  haproxy_conf:
    driver: local
  data_mariadb:
    driver: local
  redis_cache:
    driver: local
  openldap_data:
    driver: local
  files_owncloud:
    driver: local 